apiVersion: v1
kind: Service
metadata:
  name: asso1
spec:
  type: LoadBalancer
  selector:
    app: asso1
  ports:
  - port: 3333
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asso1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: asso1
  template:
    metadata:
      labels:
        app: asso1
    spec:
      containers:
      - name: asso1
        image: openlab29/asso1
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
